import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
c1 = ['#E2572C','#F4E4C3']
c2 = ['#AB0012','#1C1919']
df =  pd.read_excel('data.xlsx')
print(df.head(10))
print(df.info())
print(df.describe())
print(df.isnull().sum())
df['Item'] = df['Item'].fillna('Unknown')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].median())
df['Payment Method'] = df['Payment Method'].fillna('Unknown')
df['Location'] = df['Location'].fillna('Unknown')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
df['Transaction Date'] = df['Transaction Date'].fillna(method='ffill')
print(df.isnull().sum())

top_selliing = df.groupby('Item')['Total Spent'].sum()
top_selliing = top_selliing.sort_values(ascending=False).head(5)
print(top_selliing)
plt.figure(figsize=(15,15))
plt.barh(top_selliing.index,top_selliing.values,color=['#E2572C','#F4E4C3','#AB0012','#1C1919','#FEC700'])
plt.title('Top 5 Products Based On The Revenue Made')
plt.xlabel('Revenue Made')
plt.ylabel('Items Sold')
plt.grid(color='black',linestyle='--',linewidth='0.3')
plt.savefig('Top 5 Items.png')
plt.show()

df['Month'] = df['Transaction Date'].dt.to_period('M')
time_and_sales = df.groupby('Month')['Total Spent'].sum()
print(time_and_sales)
plt.figure(figsize=(10,10))
time_and_sales.plot(marker='o')
plt.title('Sales Over Time')
plt.xlabel('Months')
plt.ylabel('Revenue Made')
plt.grid(linestyle='--',linewidth='0.5')
plt.savefig('Sales Over Time.png')
plt.show()

top_locations = df.groupby('Location')['Total Spent'].sum()
top_locations = top_locations.sort_values(ascending=False).head(3)
plt.figure(figsize=(10,10))
plt.bar(top_locations.index,top_locations.values,color=['#AB0012','#1C1919','#E2572C','#F4E4C3'])
plt.title('Top 5 Locations Based On Revenue')
plt.xlabel('Locations')
plt.ylabel('Revenue Made')
plt.grid(linestyle='--',linewidth='0.5')
plt.savefig('Top 5 Locations.png')
plt.show()
df['Payment Method'] = df['Payment Method'].replace({'ERROR' : 'Unknown','UNKNOWN' : 'Unknown'})
payment_methods = df['Payment Method'].value_counts()
print(payment_methods)
plt.figure(figsize=(5,5))
plt.pie(payment_methods, autopct='%1.1f%%' , labels=['Unknown', 'Digital Wallet', 'Credit Card', 'Cash'], colors=['#AB0012','#1C1919','#E2572C','#F4E4C3'])
plt.savefig('Payment Methods.png')
plt.show()